name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-review:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR has been reviewed
        id: review-check
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const approved = reviews.some(review => review.state === 'APPROVED');
            
            if (!approved) {
              core.setFailed('PR has not been reviewed yet.');
            }
